
web:
    build: .
    ports:
        - 80

loadbalancer:
    image: dockercloud/haproxy:latest
    links:
        - web
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - 8080:80
